### ISSUE TITLE
PHPUnit errors in SF5 when injecting service

### ISSUE THREAD

**Issue by javisasan** [nelmio/NelmioSolariumBundle#106]
Hi,

I'm having some issues when using this bundle as a service in SF5. Service is configured as follows:

![image](https://user-images.githubusercontent.com/1962128/89101024-a1eb6780-d3fc-11ea-8199-c1f53b98be40.png)

I need to use ServiceRegistry, so in my class I inject it:

![image](https://user-images.githubusercontent.com/1962128/89101052-d7905080-d3fc-11ea-832d-8fc6b435134e.png)

But when passing tests, I'm having this output:

![image](https://user-images.githubusercontent.com/1962128/89101063-fd1d5a00-d3fc-11ea-944b-8a433f6cbb71.png)

As you can see, tests are passing OK, but a lot of warnings are appearing.

Maybe I'm not decraring properly the service?

By the way, my yaml config file:

```
nelmio_solarium:
    endpoints:
        foo:
            scheme: http
            host: '%env(resolve:SOLR_HOST)%'
            port: 8983
            path: /
            core: Foo_all
        bar:
            scheme: http
            host: '%env(resolve:SOLR_HOST)%'
            port: 8983
            path: /
            core: Bar_all
    clients:
        foo:
            endpoints: [foo]
        bar:
            endpoints: [bar]
```

Thanks in advance and hope you're allright,

Javi
