### ISSUE TITLE
install through composer causes error 

### ISSUE THREAD

**Issue by omizzy** [nelmio/NelmioSolariumBundle#17]
I am perhaps overlooking something simple, but what am I missing here...

composer.json:
...
    "require":           {
                                     ...
                                     "nelmio/solarium-bundle":           "dev-master",
                                     ...
...

app/config/config.yml:
imports:
    - { resource: services.yml }

app/config/services.yml:
...
    nelmio_solarium:
        client:
            class: Solarium_Client
        adapter:
            class: Solarium_Client_Adapter_Http
            host: 127.0.0.1
            port: 8983
            path: /solr
            timeout: 5
            cores:
                core0: core0

(produced by running 'composer update') vendor/composer/autoload_namespaces.php:
...
return array(
    ...
    'Solarium' => $vendorDir . '/solarium/solarium/library/',
    ...
    'Nelmio\SolariumBundle' => $vendorDir . '/nelmio/solarium-bundle/',
    ...
);
...

composer update output:
$ composer update
Loading composer repositories with package information
Updating dependencies
Generating autoload files

  [Symfony\Component\DependencyInjection\Exception\RuntimeException]  
  The definition for "nelmio_solarium" has no class. If you intend to inject this service dynamically at runtime, please mark it as synthetic=true. If this is an abstract definition solely used by child definitions, please add abstract=true, otherwise specify a class to get rid of this error.

I change the services.yml config to the following:
    nelmio_solarium:
# client:

```
     class: Solarium_Client
    adapter:
        class: Solarium_Client_Adapter_Http
        host: 127.0.0.1
        port: 8983
        path: /solr
        timeout: 5
        cores:
            core0: core0
```

Everything runs as expected; I am left perplexed. Can someone provide some insight?
