### ISSUE TITLE
URI instead bunch of options in config

### ISSUE THREAD

**Issue by wiistriker** [nelmio/NelmioSolariumBundle#19]
How do you think, should we create config parameter which can replace all host, port, path, etc.

For example:

```
clients:
    default:
        host: localhost
        port: 8983
        path: /solr
        core: active
        timeout: 5
```

Could be minimized to:

```
clients:
    default:
        uri: http://localhost:8983/solr/active
```

And inside Extension we can parse this string.

Now i have many solr instancies in my project and i need to create very large amount solr-related params in my parameters.yml!
