### ISSUE TITLE
Call to undefined method get()

### ISSUE THREAD

**Issue by Kue2** [nelmio/NelmioSolariumBundle#46]
Hi all,
I'm new to Symfony and NelmioSolarium.
I have followed the steps of Installation Guide (added NelmioSolariumBundle to composer, updated composer, added NelmioSolariumBundle to AppKernel.php).

Then I have added these lines to app/config/config.yml:

```
nelmio_solarium: ~

nelmio_solarium:
    endpoints:
        default:
            host: localhost
            port: 8983
            path: /solr
            core: active
            timeout: 5
    clients:
        default:
            endpoints: [default]
```

But I get the error "call to undefined method get()" on this line:

```
       $client = $this->get('solarium.client');
```

I think I'm doing something wrong with my configuration.

Can you help me?
Thank you in advance!
