### ISSUE TITLE
Error: Unrecognized option "scheme" under "nelmio_solarium.endpoints.another"

### ISSUE THREAD

**Issue by royopa** [nelmio/NelmioSolariumBundle#51]
```yaml
nelmio_solarium:
    endpoints:
        default:
            scheme: http
            host: 10.4.2.103
            port: 8983
            path: /solr
            core: sicde_1
            timeout: 5
        another:
            scheme: http
            host: 10.4.2.103
            port: 8983
            path: /solr
            core: sicde_2
            timeout: 5
    clients:
        default:
            endpoints: [default, another]
```

InvalidConfigurationException in ArrayNode.php line 309:
Unrecognized option "scheme" under "nelmio_solarium.endpoints.another"
