### ISSUE TITLE
connect through proxy with basic authentication

### ISSUE THREAD

**Issue by micheledibenedetto7** [nelmio/NelmioSolariumBundle#84]
Hi, this is my configuration of the bundle connecting to solr with basic authentication enbled and everything works fine:
```
nelmio_solarium:
    endpoints:
        default:
            host: user:pass@solr_host
            core: solr_core
            scheme: http
            port: 8983
            path: /solr
            # timeout: 5
    clients:
        default:
            endpoints: [default]
```
how can i configure this to pass through a proxy if needed? cause i think it will be needed. thanks in advance!
